---
outdir: 'deepsinv_alt_16const'
data_hyperparams:
  root: '../data/jetid'
  nconst: 16
  feats: "ptetaphi"
  norm: "robust"
  torch_dataloader:
    batch_size: 256
    shuffle: True
    num_workers: 8

model_type: "ds_invariant"

model_hyperparams:
  input_dim: 3
  phi_layers: [32, 32]
  rho_layers: [32]
  activ: "relu"
  aggreg: "mean"
  dropout: -1
  output_dim: 5

training_hyperparams:
  lr: 0.0029
  lr_patience: 15
  epochs: 1000
  weight_decay: 0.0000001
  loss: "ce"
  # clip_grad: 5
  early_stopping: 30
  permute: False
