---
define: &sampling 100
define: &classes 40
define: &temp 4

outdir: 'dgcnn_to_deepsinv_T4_100p'
data_hyperparams:
  pc_rootdir: '../data/ModelNet40_100p'
  classes: *classes
  pretransforms:
    norm: True
    sampling: *sampling
  transforms: null
  torch_dataloader:
    batch_size: 128
    shuffle: True
    num_workers: 8

teacher: "trained_models/dgcnn_100p_wang_tinv/"
teacher_seed: 42

model_type: "ds_invariant"

model_hyperparams:
  input_dim: 3
  phi_layers: [256, 256, 256]
  rho_layers: [256]
  activ: "tanh"
  aggreg: "max"
  dropout: 0.5
  output_dim: *classes


distill_hyperparams:
  lr: 0.001
  lr_patience: 15
  epochs: 1000
  early_stopping: 30
  alpha: 0
  temp: *temp
